export interface VideoDeviceInfoPageQuery {
  deviceIdentification?: string; // 设备标识
  deviceName?: string; // 设备名称
  customName?: string; // 自定义名称
  mediaIdentification?: string; // 媒体唯一标识
  manufacturer?: string; // 厂商
  model?: string; // 型号
  firmware?: string; // 固件版本
  transport?: string; // 传输协议
  streamMode?: string; // 数据流传输模式
  onlineStatus?: boolean; // 是否在线
  registerTime?: string; // 注册时间
  keepaliveTime?: string; // 心跳时间
  ip?: string; // IP
  port?: number; // 端口
  wanIp?: string; // 公网IP
  lanIp?: string; // 局域网IP
  hostAddress?: string; // 访问地址
  expires?: number; // 注册有效期
  subscribeCycleForCatalog?: boolean; // 目录订阅
  subscribeCycleForMobilePosition?: boolean; // 移动设备位置订阅
  subscribeCycleForAlarm?: boolean; // 报警订阅
  mobilePositionSubmissionInterval?: number; // 位置信息上报间隔
  charset?: string; // 字符集
  ssrcCheck?: boolean; // ssrc校验
  geoCoordSys?: string; // 地理坐标系
  sdpIp?: string; // 收流IP
  localIp?: string; // SIP交互IP
  password?: string; // 设备密码
  asMessageChannel?: boolean; // 是否作为消息通道
  keepaliveIntervalTime?: number; // 心跳间隔
  keepaliveTimeoutCount?: number; // 心跳超时次数
  positionCapability?: number; // 定位功能支持情况
  broadcastPushAfterAck?: boolean; // 控制语音对讲
  ability?: string; // 能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceInfoSaveVO {
  deviceIdentification?: string; // 设备标识
  deviceName?: string; // 设备名称
  customName?: string; // 自定义名称
  mediaIdentification?: string; // 媒体唯一标识
  manufacturer?: string; // 厂商
  model?: string; // 型号
  firmware?: string; // 固件版本
  transport?: string; // 传输协议
  streamMode?: string; // 数据流传输模式
  onlineStatus?: boolean; // 是否在线
  registerTime?: string; // 注册时间
  keepaliveTime?: string; // 心跳时间
  ip?: string; // IP
  port?: number; // 端口
  wanIp?: string; // 公网IP
  lanIp?: string; // 局域网IP
  hostAddress?: string; // 访问地址
  expires?: number; // 注册有效期
  subscribeCycleForCatalog?: boolean; // 目录订阅
  subscribeCycleForMobilePosition?: boolean; // 移动设备位置订阅
  subscribeCycleForAlarm?: boolean; // 报警订阅
  mobilePositionSubmissionInterval?: number; // 位置信息上报间隔
  charset?: string; // 字符集
  ssrcCheck?: boolean; // ssrc校验
  geoCoordSys?: string; // 地理坐标系
  sdpIp?: string; // 收流IP
  localIp?: string; // SIP交互IP
  password?: string; // 设备密码
  asMessageChannel?: boolean; // 是否作为消息通道
  keepaliveIntervalTime?: number; // 心跳间隔
  keepaliveTimeoutCount?: number; // 心跳超时次数
  positionCapability?: number; // 定位功能支持情况
  broadcastPushAfterAck?: boolean; // 控制语音对讲
  ability?: string; // 能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceInfoUpdateVO {
  id: string;
  deviceIdentification?: string; // 设备标识
  deviceName?: string; // 设备名称
  customName?: string; // 自定义名称
  mediaIdentification?: string; // 媒体唯一标识
  manufacturer?: string; // 厂商
  model?: string; // 型号
  firmware?: string; // 固件版本
  transport?: string; // 传输协议
  streamMode?: string; // 数据流传输模式
  onlineStatus?: boolean; // 是否在线
  registerTime?: string; // 注册时间
  keepaliveTime?: string; // 心跳时间
  ip?: string; // IP
  port?: number; // 端口
  wanIp?: string; // 公网IP
  lanIp?: string; // 局域网IP
  hostAddress?: string; // 访问地址
  expires?: number; // 注册有效期
  subscribeCycleForCatalog?: boolean; // 目录订阅
  subscribeCycleForMobilePosition?: boolean; // 移动设备位置订阅
  subscribeCycleForAlarm?: boolean; // 报警订阅
  mobilePositionSubmissionInterval?: number; // 位置信息上报间隔
  charset?: string; // 字符集
  ssrcCheck?: boolean; // ssrc校验
  geoCoordSys?: string; // 地理坐标系
  sdpIp?: string; // 收流IP
  localIp?: string; // SIP交互IP
  password?: string; // 设备密码
  asMessageChannel?: boolean; // 是否作为消息通道
  keepaliveIntervalTime?: number; // 心跳间隔
  keepaliveTimeoutCount?: number; // 心跳超时次数
  positionCapability?: number; // 定位功能支持情况
  broadcastPushAfterAck?: boolean; // 控制语音对讲
  ability?: string; // 能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceInfoResultVO {
  echoMap?: any;
  id?: string; // 唯一标识符
  createdTime?: string; // 创建时间
  createdBy?: string; // 创建人
  updatedTime?: string; // 最后修改时间
  updatedBy?: string; // 最后修改人
  deviceIdentification?: string; // 设备标识
  deviceName?: string; // 设备名称
  customName?: string; // 自定义名称
  mediaIdentification?: string; // 媒体唯一标识
  manufacturer?: string; // 厂商
  model?: string; // 型号
  firmware?: string; // 固件版本
  transport?: string; // 传输协议
  streamMode?: string; // 数据流传输模式
  onlineStatus?: boolean; // 是否在线
  registerTime?: string; // 注册时间
  keepaliveTime?: string; // 心跳时间
  ip?: string; // IP
  port?: number; // 端口
  wanIp?: string; // 公网IP
  lanIp?: string; // 局域网IP
  hostAddress?: string; // 访问地址
  expires?: number; // 注册有效期
  subscribeCycleForCatalog?: boolean; // 目录订阅
  subscribeCycleForMobilePosition?: boolean; // 移动设备位置订阅
  subscribeCycleForAlarm?: boolean; // 报警订阅
  mobilePositionSubmissionInterval?: number; // 位置信息上报间隔
  charset?: string; // 字符集
  ssrcCheck?: boolean; // ssrc校验
  geoCoordSys?: string; // 地理坐标系
  sdpIp?: string; // 收流IP
  localIp?: string; // SIP交互IP
  password?: string; // 设备密码
  asMessageChannel?: boolean; // 是否作为消息通道
  keepaliveIntervalTime?: number; // 心跳间隔
  keepaliveTimeoutCount?: number; // 心跳超时次数
  positionCapability?: number; // 定位功能支持情况
  broadcastPushAfterAck?: boolean; // 控制语音对讲
  ability?: string; // 能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}
