export interface VideoDeviceChannelPageQuery {
  deviceIdentification?: string; // 设备标识
  channelIdentification?: string; // 通道标识
  streamIdentification?: string; // 码流标识
  channelType?: number; // 通道类型
  streamType?: string; // 码流类型
  channelName?: string; // 通道名称
  manufacturer?: string; // 厂商
  model?: string; // 型号
  block?: string; // 警区
  provinceCode?: string; // 省,直辖市编码
  cityCode?: string; // 市编码
  regionCode?: string; // 行政区划编码
  fullAddress?: string; // 位置
  latitude?: string; // 纬度
  longitude?: string; // 经度
  safetyWay?: number; // 信令安全模式
  registerWay?: number; // 注册方式
  certNum?: string; // 证书序列号
  certStatus?: number; // 证书有效标识
  certInvalidReasonCode?: string; // 证书无效原因码
  certExpiryTime?: string; // 证书有效期截止时间
  secrecy?: number; // 保密属性
  ipAddress?: string; // 设备/系统IPv4/IPv6地址
  port?: number; // 设备/系统端口
  password?: string; // 设备口令
  onlineStatus?: boolean; // 是否在线
  hasAudio?: boolean; // 是否含有音频
  ptzType?: number; // 摄像机结构类型
  positionType?: number; // 摄像机位置类型扩展
  roomType?: number; // 摄像机安装位置类型
  useType?: number; // 用途属性类型
  supplyLightType?: number; // 摄像机补光属性类型
  directionType?: number; // 摄像机监视方位(光轴方向)属性类型
  resolution?: string; // 分辨率
  downloadSpeed?: string; // 下载倍速
  svcSpaceSupportMod?: number; // 空域编码能力
  svcTimeSupportMode?: number; // 时域编码能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceChannelSaveVO {
  deviceIdentification?: string; // 设备标识
  channelIdentification?: string; // 通道标识
  streamIdentification?: string; // 码流标识
  channelType?: number; // 通道类型
  streamType?: string; // 码流类型
  channelName?: string; // 通道名称
  manufacturer?: string; // 厂商
  model?: string; // 型号
  block?: string; // 警区
  provinceCode?: string; // 省,直辖市编码
  cityCode?: string; // 市编码
  regionCode?: string; // 行政区划编码
  fullAddress?: string; // 位置
  latitude?: string; // 纬度
  longitude?: string; // 经度
  safetyWay?: number; // 信令安全模式
  registerWay?: number; // 注册方式
  certNum?: string; // 证书序列号
  certStatus?: number; // 证书有效标识
  certInvalidReasonCode?: string; // 证书无效原因码
  certExpiryTime?: string; // 证书有效期截止时间
  secrecy?: number; // 保密属性
  ipAddress?: string; // 设备/系统IPv4/IPv6地址
  port?: number; // 设备/系统端口
  password?: string; // 设备口令
  onlineStatus?: boolean; // 是否在线
  hasAudio?: boolean; // 是否含有音频
  ptzType?: number; // 摄像机结构类型
  positionType?: number; // 摄像机位置类型扩展
  roomType?: number; // 摄像机安装位置类型
  useType?: number; // 用途属性类型
  supplyLightType?: number; // 摄像机补光属性类型
  directionType?: number; // 摄像机监视方位(光轴方向)属性类型
  resolution?: string; // 分辨率
  downloadSpeed?: string; // 下载倍速
  svcSpaceSupportMod?: number; // 空域编码能力
  svcTimeSupportMode?: number; // 时域编码能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceChannelUpdateVO {
  id: string;
  deviceIdentification?: string; // 设备标识
  channelIdentification?: string; // 通道标识
  streamIdentification?: string; // 码流标识
  channelType?: number; // 通道类型
  streamType?: string; // 码流类型
  channelName?: string; // 通道名称
  manufacturer?: string; // 厂商
  model?: string; // 型号
  block?: string; // 警区
  provinceCode?: string; // 省,直辖市编码
  cityCode?: string; // 市编码
  regionCode?: string; // 行政区划编码
  fullAddress?: string; // 位置
  latitude?: string; // 纬度
  longitude?: string; // 经度
  safetyWay?: number; // 信令安全模式
  registerWay?: number; // 注册方式
  certNum?: string; // 证书序列号
  certStatus?: number; // 证书有效标识
  certInvalidReasonCode?: string; // 证书无效原因码
  certExpiryTime?: string; // 证书有效期截止时间
  secrecy?: number; // 保密属性
  ipAddress?: string; // 设备/系统IPv4/IPv6地址
  port?: number; // 设备/系统端口
  password?: string; // 设备口令
  onlineStatus?: boolean; // 是否在线
  hasAudio?: boolean; // 是否含有音频
  ptzType?: number; // 摄像机结构类型
  positionType?: number; // 摄像机位置类型扩展
  roomType?: number; // 摄像机安装位置类型
  useType?: number; // 用途属性类型
  supplyLightType?: number; // 摄像机补光属性类型
  directionType?: number; // 摄像机监视方位(光轴方向)属性类型
  resolution?: string; // 分辨率
  downloadSpeed?: string; // 下载倍速
  svcSpaceSupportMod?: number; // 空域编码能力
  svcTimeSupportMode?: number; // 时域编码能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}

export interface VideoDeviceChannelResultVO {
  echoMap?: any;
  id?: string; // 唯一标识符
  createdTime?: string; // 创建时间
  createdBy?: string; // 创建人
  updatedTime?: string; // 最后修改时间
  updatedBy?: string; // 最后修改人
  deviceIdentification?: string; // 设备标识
  channelIdentification?: string; // 通道标识
  streamIdentification?: string; // 码流标识
  channelType?: number; // 通道类型
  streamType?: string; // 码流类型
  channelName?: string; // 通道名称
  manufacturer?: string; // 厂商
  model?: string; // 型号
  block?: string; // 警区
  provinceCode?: string; // 省,直辖市编码
  cityCode?: string; // 市编码
  regionCode?: string; // 行政区划编码
  fullAddress?: string; // 位置
  latitude?: string; // 纬度
  longitude?: string; // 经度
  safetyWay?: number; // 信令安全模式
  registerWay?: number; // 注册方式
  certNum?: string; // 证书序列号
  certStatus?: number; // 证书有效标识
  certInvalidReasonCode?: string; // 证书无效原因码
  certExpiryTime?: string; // 证书有效期截止时间
  secrecy?: number; // 保密属性
  ipAddress?: string; // 设备/系统IPv4/IPv6地址
  port?: number; // 设备/系统端口
  password?: string; // 设备口令
  onlineStatus?: boolean; // 是否在线
  hasAudio?: boolean; // 是否含有音频
  ptzType?: number; // 摄像机结构类型
  positionType?: number; // 摄像机位置类型扩展
  roomType?: number; // 摄像机安装位置类型
  useType?: number; // 用途属性类型
  supplyLightType?: number; // 摄像机补光属性类型
  directionType?: number; // 摄像机监视方位(光轴方向)属性类型
  resolution?: string; // 分辨率
  downloadSpeed?: string; // 下载倍速
  svcSpaceSupportMod?: number; // 空域编码能力
  svcTimeSupportMode?: number; // 时域编码能力
  extendParams?: string; // 扩展参数
  remark?: string; // 备注
  createdOrgId?: string; // 创建人组织
}
